### PR TITLE
Recall socket recv until get a complete response.

### PR DESCRIPTION
**Pull request by ccatterina**
Socket recv waits until it gets some data from the host but
not necessarily the entire response that can be fragmented in
many packets. In this case it receives an incomplete frame
that is rejected by the frame handler.
This commit solves this issue by recalling socket recv until
get a complete modbus response.

### CODE REVIEW

**Comment by bje-** [comment]
+1

**Comment by bje-** [comment]
This seems like a rather important patch (which seems to work well, for me at least). Without it, pymodbus for TCP slaves hardly ever works. My read register calls return None a lot of the time.  I am amazed no one else sees this issue.  I am happy to do the work to bring it up to line with master.

**Comment by ccatterina** [comment]
Hi @bje- , i have already updated the commit in a branch of my repository but i have not tested it yet. I will update the PR as soon as possible.

**Comment by ccatterina** [comment]
Updated.

**Comment by dhoomakethu** [comment]
Thank you, I will add this to 1.3.1 milestone.

**Comment by dhoomakethu** [comment]
would also partially fix #175

**Comment by dhoomakethu** [comment]
@ccatterina  Just to highlight a bug here with this fix, when there is an exception received from the modbus device, client will be struck in an eternal while loop or ends with socket error ,resulting in a None being returned back. I will have to revert this change.

**Comment by ccatterina** [comment]
Oh, rigth, i'm sorry that i didn't notice the bug before. I will try to fix this as soon as possible, meanwhile, revert it.

**Pull request merged**
