### PR TITLE
Updated datastore Simulator.

### PR DESCRIPTION
**Pull request by janiversen**
100% test coverage.
Solved several problems
Added possibility for arguments in the actions
Cleaned/optimized the http_server code

add TODO.md for open simulator tasks.

### CODE REVIEW

**Comment by janiversen** [comment]
@dhoomakethu  can you please take a fast look at the screenshot and tell me if I have covered the current functionality of the REPL server ? 
I have tried to look in the source code as well as documentation, but I might have missed something.

I am currently adding the functionality behind the scenes, mainly through 2 hooks: request_tracer (new, called when entering execute) and response_manipulator (called as you know it). I am also having a student earning points while helping write some more detailed documentation.

The REPL server works without changes, as I have done all in parallel (for now).
Captura de pantalla 2023-01-04 a las 19 40 23

Thanks in advance for any comments.

**Comment by dhoomakethu** [comment]
@janiversen guess `split response` is new, apart from that all other options looks good. You have it covered. Thanks

**Comment by janiversen** [comment]
Thanks, yes "split" is new, something I have wanted for a long time to test that our client can handle it.

I am nearly finished with the integration into the standard server, right now I keep it as it is, but it needs to be converted to async.

**Comment by janiversen** [comment]
work continue here: https://github.com/janiversen/pymodbus_nextGen/pull/1

**Pull request closed without merging**
