### PR TITLE
Dev3.7 async keyword changes

### PR DESCRIPTION
**Pull request by dices**
Renamed pymodbus.server.async to pymodbus.server.asynchronous
Modified asyncio.async to use asyncio.ensure_future
Added missing prompt_toolkit dependency to requirements-docs.txt
Updated references in documentation
Updated examples

### CODE REVIEW

**Comment by dices** [comment]
Just removed the python3.7 configuration from Travis while the 3.7 support is added to it

**Comment by NovapaX** [comment]
I would love it if this could get merged into 3.7 branch 
(and maybe merge latest release into dev 3.7 too?)

That way I could easily test this in my project.

**Comment by dhoomakethu** [comment]
@NovapaX I can merge this in to 3.7 branch in some time, once I sync up the latest on master to dev3.7 branch.

**Comment by dhoomakethu** [comment]
@dices  Thanks for fixing the merge conflicts. I will take some time over the weekend to review and merge this in to the `dev3.7` branch. Appreciate your effort.

**Pull request merged**
