### PR TITLE
Porting to Python3

### PR DESCRIPTION
**Pull request by vinichou94**
Hi bashwork,

I finished the porting to Python 3. Normally everything is good.
All tests are passed and it compiled without error.
Tell me if you find any problems.

Regards

### CODE REVIEW

**Comment by Bobby-Miller** [comment]
Awesome!

The test server/client worked on my system - python 3.6

Can't wait to try this at work one some Modbus hardware. Thank you so much!!!

**Comment by vinichou94** [comment]
Thanks !!
Good news, can you keep me informed about your tests at work please?
Currently, I haven't access to Modbus hardware.

**Comment by Bobby-Miller** [comment]
Absolutely. 
This is my first dive into twisted, and my mind is a little warped by the code structure, so it may take me a little time. But I've been wanting this excuse for a long time. Modbus is the only communication protocol for a few of my PLCs, and I've been too stubborn to jump back to python 2.

I'll let you know as soon as I have results.

Thanks again!

...If I might be so bold, why put so much work into a protocol you have no hardware for? Just curious...

**Comment by vinichou94** [comment]
I understand, it's a lot different. I think but you'll see it's really powerfull!!
Really? Which Modbus do you use? Over TCP or Serial?
You're right, more and more module has been ported to Python3 now.

Great, I'm looking forward results.

You're welcome.

No problem, I'm an unconditional fan of python, I would help to port module on Python3 and I had time. I saw it here http://fedora.portingdb.xyz/#mispackaged. I already used it and I know it very well so I thought people would need it on Python3. That's all =)

**Comment by Bobby-Miller** [comment]
Very cool. All our modbus is TCP.

Early use is good - I am able to pull a few holding registers from a PLC here. I will need to research the module a little more to start configuring the endian and such.

Will keep you posted.

**Comment by vinichou94** [comment]
Great!! I'm happy to know it.
Thanks for your feedback.

**Comment by oz123** [comment]
Any chance of merging this soon?

**Comment by dhoomakethu** [comment]
@vinichou94, Thanks for the PR , there is another PR #72 which is approved for merger . And it would take some more time before we could look in to this PR and do a merge.

**Comment by dhoomakethu** [comment]
btw, I see that you have raised the PR against riptideio:master, instead of riptideio:python3. Could you please raise against the correct branch please ?

**Comment by curtisdave** [comment]
Just want to add a note here that I have been using this PR with Python 3.4 and Twisted 17.1.0, and everything seems to be working for me as I expect it to, although I'm not exercising very much of the code yet, mainly async TCP/IP client.

**Comment by dhoomakethu** [comment]
@curtisdave thanks for the update.

**Comment by dhoomakethu** [comment]
Merged as part of or #164

**Pull request closed without merging**
