### PR TITLE
simplify if condition

### PR DESCRIPTION
**Pull request by imba-tjd**

### CODE REVIEW

**Comment by janiversen** [comment]
hmmm a bit strange, but something is wrong here.

**Comment by imba-tjd** [comment]
Try again. I copied and pasted. Turns out there is one place different

**Comment by janiversen** [comment]
You should run pytest before submitting, that saves us all time.

**Review by janiversen — APPROVED** [review]
Thanks

**Comment by janiversen** [comment]
Thanks.

**Pull request merged**
