### PR TITLE
Retry loop fix #404

### LINKED ISSUE #404: better retries for incorrect data received
### Versions

* Python: 2.7.9, 3.4.2
* OS: Debian 8.10
* Pymodbus: 2.2.0
* Modbus Hardware (if used):  Qeed TCP bridge and modbus RTU meters (QE-POWER-T-STD, QE-BR-ETH485 datasheets on http://www.qeed.it/)

### Pymodbus Specific
* Client: tcp - sync

### Description

When I try to read some meters across a TCP bridge (so I use ModbusTcpClient) sometimes (randomly, probably due to buggy firmware) I received inconsistent reply eg. the zero response you can see in the attached Wireshark capture.
In this cases I expected a retry, instead I receive an exception or response.isError() = True but no retries. In some cases I obtain an exception, in some other (with the same responses!) isError().
I noticed the retry loop (```while retries > 0 ```) in transaction.py works with raw replies and expect an empty reply to retry. In my case the response is always non-empty, but need to be validated for lenght and unit id to verify if it's a valid response (I think self.client.framer.processIncomingPacket, unluckily done only after the reply loop).

### Code and Logs

isError() = True case:

```python
2019-04-10 17:34:51,855 pymodbus.transaction modbus_tcp.32 DEBUG Current transaction state - IDLE
2019-04-10 17:34:51,856 pymodbus.transaction modbus_tcp.32 DEBUG Running transaction 1
2019-04-10 17:34:51,856 pymodbus.transaction modbus_tcp.32 DEBUG SEND: 0x0 0x1 0x0 0x0 0x0 0x6 0x2 0x3 0x0 0xf4 0x0 0x4
2019-04-10 17:34:51,857 pymodbus.client.sync modbus_tcp.32 DEBUG New Transaction state 'SENDING'
2019-04-10 17:34:51,857 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2019-04-10 17:34:51,897 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'WAITING FOR REPLY' to 'PROCESSING REPLY'
2019-04-10 17:34:51,897 pymodbus.transaction modbus_tcp.32 DEBUG RECV: 0x0 0x1 0x0 0x0 0x0 0x5 0x0 0x0 0x0 0x0 0x0
2019-04-10 17:34:51,898 pymodbus.transaction modbus_tcp.32 DEBUG Getting transaction 1
2019-04-10 17:34:51,898 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'

```

another isError() = True:

```python
2019-04-10 17:42:54,501 pymodbus.transaction modbus_tcp.32 DEBUG Current transaction state - TRANSACTION_COMPLETE
2019-04-10 17:42:54,501 pymodbus.transaction modbus_tcp.32 DEBUG Running transaction 37
2019-04-10 17:42:54,502 pymodbus.transaction modbus_tcp.32 DEBUG SEND: 0x0 0x25 0x0 0x0 0x0 0x6 0x2 0x3 0x1 0x74 0x0 0x2
2019-04-10 17:42:54,502 pymodbus.client.sync modbus_tcp.32 DEBUG New Transaction state 'SENDING'
2019-04-10 17:42:54,502 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2019-04-10 17:42:54,527 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'WAITING FOR REPLY' to 'PROCESSING REPLY'
2019-04-10 17:42:54,527 pymodbus.transaction modbus_tcp.32 DEBUG RECV: 0x0 0x25 0x0 0x0 0x0 0x6 0x81 0x20 0xd0 0x6a 0xf9 0x15
2019-04-10 17:42:54,527 pymodbus.transaction modbus_tcp.32 DEBUG Getting transaction 37
2019-04-10 17:42:54,527 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'PROCESSING REPLY' to 'TRANSACTION_COMPLETE'

```

Exception:

```python
2019-04-10 17:32:38,376 pymodbus.transaction modbus_tcp.32 DEBUG Current transaction state - IDLE
2019-04-10 17:32:38,377 pymodbus.transaction modbus_tcp.32 DEBUG Running transaction 1
2019-04-10 17:32:38,377 pymodbus.transaction modbus_tcp.32 DEBUG SEND: 0x0 0x1 0x0 0x0 0x0 0x6 0x2 0x3 0x0 0xf4 0x0 0x4
2019-04-10 17:32:38,377 pymodbus.client.sync modbus_tcp.32 DEBUG New Transaction state 'SENDING'
2019-04-10 17:32:38,378 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'SENDING' to 'WAITING FOR REPLY'
2019-04-10 17:32:38,399 pymodbus.transaction modbus_tcp.32 DEBUG Changing transaction state from 'WAITING FOR REPLY' to 'PROCESSING REPLY'
2019-04-10 17:32:38,399 pymodbus.transaction modbus_tcp.32 DEBUG RECV: 0x0 0x1 0x0 0x0 0x0 0x4 0x2 0x0 0x0 0x0
2019-04-10 17:32:38,400 pymodbus.factory modbus_tcp.32 ERROR Unable to decode response Modbus Error: Unknown response 0
2019-04-10 17:32:38,400 pymodbus.transaction modbus_tcp.32 ERROR Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/home/andrea/LWE/MPO/Myna/wolf/pymodbus/transaction.py", line 177, in execute
    request.unit_id)
  File "/home/andrea/LWE/MPO/Myna/wolf/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/home/andrea/LWE/MPO/Myna/wolf/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request

```

### PR DESCRIPTION
**Pull request by wildstray**
Fully rewrited retry loop for no response and invalid response. These code almost fully solve our issues with a poor firmware energy measure field, surely Modbus specifications have many conditional and gaps about transaction retries so these might go over and above specs. NB: Tested with Modbus TCP only at now!

### CODE REVIEW

**Comment by dhoomakethu** [comment]
@wildstray Please resolve the conflicts. Thanks

**Comment by wildstray** [comment]
I need to understand how to submit a PR at this point. Excuse me but I haven't so many troubles amd complications on the past when I submittetd PR to other project. I don't understand the cause of that conflicts and I already adapted it for dev branch. Keep in mind that I'm using the code I submitted in production environment (and I submitted it to our fork of pymodbus without problems) and I'm developing that for work purpose and for my company: I cannot spend other time to work on your library especially if there is not interest ot collaboration (company policy).

**Comment by dhoomakethu** [comment]
@wildstray If you update your `dev` branch I am sure you will see these conflicts as well. I appreciate your interest in helping the project but unfortunately I am also tied up with the same constraints as yours, This is not my full time job and I try to accomodate this work when I am free. Please feel free to take your time to fix the conflicts or I will cherry pick your changes to dev branch when I get time.

**Comment by dhoomakethu** [comment]
@wildstray Can this be closed against the other PR #412 by you?

**Pull request closed without merging**
