### PR TITLE
Add TLS feature for Modbus synchronous

### PR DESCRIPTION
**Pull request by starnight**
Modbus.org released MODBUS/TCP Security Protocol Specification [1],
which focuses variant of the Mobdbus/TCP protocol utilizing Transport
Layer Security (TLS). This patch enables the Modbus over TLS feature as
ModbusTlsClient with the Python builtin module ssl - TLS/SSL wrapper for
socket objects.

[1]: http://modbus.org/docs/MB-TCP-Security-v21_2018-07-24.pdf

### CODE REVIEW

**Comment by starnight** [comment]
Rebased upon dev branch (tags/v2.3.0rc1), fixed the test errors and also increased test coverage.

**Comment by dhoomakethu** [comment]
@starnight how hard it is to implement tlsserver for morbus? Is it as simple as using `ModbusTCPServer` with `tlsframer` ?. Apologies I am taking too much time on this, I am yet to go through the specs .

**Comment by starnight** [comment]
> @starnight how hard it is to implement tlsserver for morbus? Is it as simple as using `ModbusTCPServer` with `tlsframer` ?. Apologies I am taking too much time on this, I am yet to go through the specs .

I have not study the ModbusTCPServer deeply yet.  But, I can try to jump into that. :)

**Comment by starnight** [comment]
Add **ModbusTlsServer** inheriting **ModbusTcpServer** as MODBUS TLS synchronous server with the new commit ("Implement MODBUS TLS synchronous server").  The commit also includes the tests and an example.

**Pull request merged**
