### PR TITLE
Hex values for repl arguments

### LINKED ISSUE #628: Add support for hex values in REPL client.write_registers
Modbus registers are 16-bit and sometimes it is easier to understand their values when expressed in hex.

However, in the REPL tool "pymodbus.console", it looks like you cannot use hex for the values:

> client.write_registers unit=1 address=9 values=0x0331
ValueError("invalid literal for int() with base 10: '0x0331'")

It would be nice if you could use hex like depicted above.

### PR DESCRIPTION
**Pull request by pkubanek**
Fix #628. int(x, 0) accept decimal (11), hex (0x11=17), as well as
binary (ob1100=12) and octo (0o11=9) values.

### CODE REVIEW

**Review by janiversen — APPROVED** [review]
Looks good to me, and the documentation support your claim, it would be nice though to see a couple of test cases.

Since @dhoomakethu if the expert on repl, lets hear his opinion.

**Comment by pkubanek** [comment]
I added tests for _process_args, which I have to move to module (shall not cause an issue). repl itself is sparsely covered by tests (to be decent), but that shall perhaps be another PR (to add testing for repl client and server).

**Review by dhoomakethu — APPROVED** [review]

**Comment by dhoomakethu** [comment]
Looks good,  although I would ideally want to have support only for decimal and hex and not support binary or octal as thats going to cause some confusion or not really used.

**Comment by pkubanek** [comment]
Binary values make sense for various flags encountered in Modbus devices. I would leave it that way, binary support is handy, and octal wouldn't make a big difference.

**Review by janiversen — APPROVED** [review]
LGTM.

**Comment by janiversen** [comment]
You are right repl does not have a lot of tests, so feel free to add tests. I am trying to generally cleanup the tests (and the code) but I am stuck with the client/server parts.

Feel free to ping me if you want to ping-pong on how to write the tests (I like pytest.mark.parametrice a lot)

**Pull request merged**
