### PR TITLE
Py37 migration

### PR DESCRIPTION
**Pull request by cbergmiller**
proposed fix for #320

### CODE REVIEW

**Comment by dhoomakethu** [comment]
@cbergmiller thanks for the quick PR, could you also add python3.7 to travis.yml so that the tests are run and tested on python 3.7 as well ? Thanks

**Comment by dhoomakethu** [comment]
@cbergmiller  Tests are failing

**Comment by cbergmiller** [comment]
@dhoomakethu The tests are failing at the Twisted client, which i didn't touch. And tests pass in my Windows environment. I will look into it.

**Comment by dhoomakethu** [comment]
@cbergmiller , quoting from this conversation https://github.com/riptideio/pymodbus/pull/337#issuecomment-424961455. Would you mind raising this PR against `dev3.7` branch as `riptideio:async-updates` is already merged.

**Pull request closed without merging**
