### PR TITLE
Remove twisted/tornado from doc

### PR DESCRIPTION
**Pull request by janiversen**

### CODE REVIEW

**Comment by janiversen** [comment]
@dhoomakethu can you please control that I made the changes correctly (I am not sure how to generate doc).

Since you will be doing dev4, lets include this if it works.

**Comment by dhoomakethu** [comment]
Looks like the documentation build is broken on readthedocs. I will take a stab in to this after Wednesday.
image

**Comment by janiversen** [comment]
@dhoomakethu can you please confirm, that this PR works now.

Do we somewhere have a HOW_TO document, explaining how to generate and check the documentation, of course only local ?

**Comment by dhoomakethu** [comment]
`make docs` should generate the documents locally

**Comment by janiversen** [comment]
Thanks I will try to do that.

**Pull request merged**
