### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by matthiasstraka**
Fixed several typos in source file comments

### CODE REVIEW

**Review by janiversen — APPROVED** [review]
Lgtm.

**Comment by janiversen** [comment]
Let me know once it is ready for review, looks good so far.

**Review by janiversen — APPROVED** [review]
Looks good, thanks.

Merging it, to avoid further conflicts. If you find more (or want to enhance some of the descriptions) please submit a new PR.

**Comment by matthiasstraka** [comment]
Thanks, currently I have not planned similar prs.

**Pull request merged**
