### PR TITLE
Use async/await keywords in test_server_asyncio.py

### PR DESCRIPTION
**Pull request by JamesJeffryes**
I'm planning on splitting up a fix to #513 & #467 into a couple of PRs as there's more edits than I expected.

While I was replacing the old async syntax, I took a moment to do some reformatting, remove unused imports and replace the unittest methods with pytest syntax.

### CODE REVIEW

**Comment by dhoomakethu** [comment]
@JamesJeffryes Thanks for the PR, looks like this is breaking tests in all other python versions except 3.8. Would you be able to take a look please ?

**Comment by JamesJeffryes** [comment]
Fixed most of the other builds by specifying a minimum version of 'attrs' but the xcode tests looks like they are timing out trying to install java. Maybe there's a more modern image that could be used?

**Comment by JamesJeffryes** [comment]
More general question, if this code is bound for a 3.5+ release. Should I pull out the IS_PYTHON3 checking in the tests as I go?

**Comment by JamesJeffryes** [comment]
@dhoomakethu Thoughts on the failing xcode build?

**Comment by dhoomakethu** [comment]
Will take a look, osx builds are failing off late. Could be the xcode version that is causing the issue.

**Review by dhoomakethu — APPROVED** [review]

**Pull request merged**
