### PR TITLE
Revert "Refactor/DRY: use `use_hexlify_packets`"

### PR DESCRIPTION
**Pull request by dhoomakethu**
Reverts riptideio/pymodbus#536

### CODE REVIEW

**Comment by Cougar** [comment]
Was there any problems or you just reverted because it went to master branch?

**Comment by dhoomakethu** [comment]
Yes, had to revert it because it went to master

**Comment by dhoomakethu** [comment]
Will cherry pick this with other PR

**Comment by Cougar** [comment]
dev is currently behind a master. is this intentional or should it be rebased to current master?

**Comment by dhoomakethu** [comment]
It needs to be rebased.

**Pull request merged**
