### PR TITLE
#232 fix triomotion communications

### PR DESCRIPTION
**Pull request by shayden--**
Instead of immediately discarding frame data, ModbusSocketFramer.processIncomingPacket() now saves partially received data for later processing.
ModbusSocketFramer.resetFrame() now sets self._header to the same dict as in __init__().

### CODE REVIEW

**Comment by dhoomakethu** [comment]
@shayden--  thanks for the PR. the tests are failing , would you mind fixing them please ?

**Comment by shayden--** [comment]
Of the six failing tests, five pass now.

testTCPFramerTransactionShort() failed because I removed the header length check in ModbusSocketFramer.checkFrame() unnecessarily. It's been re-added.

The following tests failed because self.assertCountEquals is not backwards compatible, the tests now use six.assertCountEquals(self,...) which passes on python2 & python3:
- testTCPProcessPackets01
- testTCPProcessPackets02
- testTCPProcessPackets03
- testTCPProcessPackets04

The last test, testTCPProcessPackets05, was designed to fail. I noticed that my patch results in the pymodbus synchronous server behaving incorrectly when junk bytes get added to the ModbusSocketFramer.buffer. Instead of throwing an exception if the frame can't be decoded, it seems to just send the response of the last good frame received. I started investigating but the changes necessary would be beyond the scope of this patch. 

I wanted input on this last test and what to do:
1. I can remove testTCPProcessPackets05 from this PR and open a new issue after more investigation. 
2. Or just drop the test if the decision is to trust TCP or the client to not mis-order or send junk frames.

**Comment by dhoomakethu** [comment]
The problem is both server and client share the same transaction methods to process the data. It would be nice if this patch, though intended at tcp client is also applicable for other clients as well (rtu , ascii and binary) and the servers. I am adding the milestone as 2.0.0 as this could affect other client and server implementation . I will see if I can spend some time to test this. But please excuse, if it gets delayed to have this merged in to the master branch.

**Comment by shayden--** [comment]
There is no rush to deploy this patch for our group, a locally patched version of v1.4.0 works right now.

I can add tests and patches to the ModbusRtuFramer, ModbusAsciiFramer and ModbusBinaryFramer so that the patch applies to all clients. I am busy for the next few weeks but will have some time to work on this later in the month.

For test `testTCPProcessPackets05` I pushed my work to https://github.com/shayden--/pymodbus/blob/dabb2bc9842779cba8285b92b52911ef2fa18f30/pymodbus/transaction.py#L478 .

I was relying on the calling `_process(...,error=True)` to cause an exception to be raised or to a return the approriate error message to the modbus client. Instead when 2 messages are sent that bracket some junk bytes, the exception object is passed as a result and the correct response from the previous message is sent instead:
**client**
> $ ./tcp-send-bytes.py
> Sending 'b'\x00\x00\x00\x00\x00\x06\xfc\x01\x00\x02\x00\x03''...
> Response 'b'\x00\x00\x00\x00\x00\x04\xfc\x01\x01\x07''
> Sending 'b'\xe0\xdf\t''...
> Response 'b'\x00\x00\x00\x00\x00\x04\xfc\x01\x01\x07''
> Sending 'b'\x00\x01\x00\x00\x00\x0b\xfc\x10\x00 \x00\x02\x04\n\x07\x10\xb4''...
> Response 'b'\x00\x00\x00\x00\x00\x03\x00\xe0\x01''

**server**

> $ ./synchronous_server.py
> DEBUG:pymodbus.server.sync:Started thread to serve client at ('127.0.0.1', 42956)
> DEBUG:pymodbus.server.sync:Client Connected [127.0.0.1:42956]
> DEBUG:pymodbus.server.sync:0x0 0x0 0x0 0x0 0x0 0x6 0xfc 0x1 0x0 0x2 0x0 0x3
> DEBUG:pymodbus.transaction:0x0 0x0 0x0 0x0 0x0 0x6 0xfc 0x1 0x0 0x2 0x0 0x3
> DEBUG:pymodbus.transaction:_process input data: b'\x01\x00\x02\x00\x03'
> DEBUG:pymodbus.factory:Factory Request[1]
> DEBUG:pymodbus.transaction:_process result: ReadBitRequest(2,3)
> DEBUG:pymodbus.datastore.context:validate[1] 3:3
> DEBUG:pymodbus.datastore.context:getValues[1] 3:3
> DEBUG:pymodbus.server.sync:send: b'000000000004fc010107'
> DEBUG:pymodbus.server.sync:0xe0 0xdf 0x9
> DEBUG:pymodbus.transaction:0xe0 0xdf 0x9
> DEBUG:pymodbus.server.sync:0x0 0x1 0x0 0x0 0x0 0xb 0xfc 0x10 0x0 0x20 0x0 0x2 0x4 0xa 0x7 0x10 0xb4
> DEBUG:pymodbus.transaction:0x0 0x1 0x0 0x0 0x0 0xb 0xfc 0x10 0x0 0x20 0x0 0x2 0x4 0xa 0x7 0x10 0xb4
> DEBUG:pymodbus.transaction:_process input data: b'\xe0\xdf\t'
> DEBUG:pymodbus.factory:Factory Request[224]
> DEBUG:pymodbus.transaction:_process result: <pymodbus.pdu.IllegalFunctionRequest object at 0x7fe356eaf470>
> DEBUG:pymodbus.server.sync:send: b'00000000000300e001'
> DEBUG:pymodbus.transaction:_process input data: b'\x10\x00 \x00\x02\x04\n\x07\x10\xb4'
> DEBUG:pymodbus.factory:Factory Request[16]
> DEBUG:pymodbus.transaction:_process result: WriteMultipleRegisterRequest 32 => 2
> DEBUG:pymodbus.datastore.context:validate[16] 33:2
> DEBUG:pymodbus.datastore.context:setValues[16] 33:2
> DEBUG:pymodbus.server.sync:send: b'000100000006fc1000200002'
> ERROR:pymodbus.server.sync:Socket error occurred [Errno 104] Connection reset by peer
> DEBUG:pymodbus.server.sync:Client Disconnected [127.0.0.1:42956]

From reading the Modbus Application Protocol Specification V1.1b, section 7, it seems like the proper thing to do is to just empty the buffer and send no response, so the error bytes will be processed by the client as a timeout. This shouldn't be hard to do, but I'll have to learn more about the pymodbus internals ( factory and pdu sections? ) to implement it.

**Comment by dhoomakethu** [comment]
@shayden-- Would you mind giving a spin on the latest `dev` and see if that solves your issue. if not I will take this up for the next release. Please sync on to the latest dev and update the PR

**Comment by shayden--** [comment]
I synced to the dev branch and installed pymodbus-2.0.0rc2 on the trio workstation for testing ( using `C:\Python36>Scripts\pip.exe install git+https://github.com/riptideio/pymodbus.git@dev` ). Will follow up with results.

**Comment by dhoomakethu** [comment]
@shayden-- Is there an update with your findings ? Can we close this PR ?

**Comment by shayden--** [comment]
I updated pymodbus to 2.0.0.rc2, started a synchronous server process, then sent tcp/modbus packets in a loop, waiting for a packet fragmentation. When a packet fragment occurred, the server threw this exception:
```
DEBUG:pymodbus.factory:Factory Request[16]
DEBUG:pymodbus.datastore.context:validate[16] 1:12
DEBUG:pymodbus.datastore.context:setValues[16] 1:12
![20180921 frame910 partialmodbuspkt 02](https://user-images.githubusercontent.com/1438247/45900673-73d38000-bdae-11e8-8663-b64085f748dc.jpg)
![20180921 frame909 partialmodbuspkt 01](https://user-images.githubusercontent.com/1438247/45900676-746c1680-bdae-11e8-8a99-6d4cf86c9487.jpg)
![20180921 frame907 fullmodbuspkt](https://user-images.githubusercontent.com/1438247/45900677-746c1680-bdae-11e8-805c-666eb3452447.jpg)



DEBUG:pymodbus.server.sync:send: b'058e0000000601100000000c'
DEBUG:pymodbus.server.sync:Handling data: 0x5 0x8f 0x0 0x0 0x0 0x1f 0x1 0x10 0x0 0x0 0x0 0xc 0x18 0x0 0x0 0x0 0x0 0x0 0x0 0x3f 0x80 0x0 0x0 0x40 0x0 0x0 0x0 0x40 0x40 0x0 0x0
DEBUG:pymodbus.framer.socket_framer:Processing: 0x5 0x8f 0x0 0x0 0x0 0x1f 0x1 0x10 0x0 0x0 0x0 0xc 0x18 0x0 0x0 0x0 0x0 0x0 0x0 0x3f 0x80 0x0 0x0 0x40 0x0 0x0 0x0 0x40 0x40 0x0 0x0
DEBUG:pymodbus.framer.socket_framer:Frame check failed, ignoring!!
DEBUG:pymodbus.server.sync:Handling data: 0x40 0x80 0x0 0x0 0x40 0xa0
DEBUG:pymodbus.framer.socket_framer:Processing: 0x40 0x80 0x0 0x0 0x40 0xa0
DEBUG:pymodbus.factory:Factory Request[64]
ERROR:pymodbus.server.sync:Socket exception occurred Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pymodbus\server\sync.py", line 177, in handle
    single=single)
  File "C:\Python36\lib\site-packages\pymodbus\framer\socket_framer.py", line 165, in processIncomingPacket
    self._process(callback, error=True)
  File "C:\Python36\lib\site-packages\pymodbus\framer\socket_framer.py", line 177, in _process
    raise InvalidMessageReceivedException(result)
pymodbus.exceptions.InvalidMessageReceivedException: Modbus Error: [Invalid Message] <pymodbus.pdu.IllegalFunctionRequest object at 0x0000000002FBBCF8>

DEBUG:pymodbus.server.sync:Client Disconnected [192.168.0.250:1027]
```
Screenshots of the ethernet frames of a full modbus packet and the fragments in wireshark are attached.

I'll try re-writing tests testTCPProcessPackets01 through testTCPProcessPackets05 for the 2.0 dev branch, and I've been trying to get travis-ci running locally in docker to run the full test suite but it's taking some time.

**Comment by dhoomakethu** [comment]
@shayden-- Thanks for the findings, I will try to reproduce the issue with sync server.

**Comment by shayden--** [comment]
I added the python script I've been using for manual testing to my fork of the issue, for your reference. 

https://github.com/shayden--/pymodbus/commit/5b5bd508db63a699aa1773cd15302edc95845f48

**Pull request closed without merging**
