### PR TITLE
Add pygments as requirement for repl.

### PR DESCRIPTION
**Pull request by janiversen**

### CODE REVIEW

**Comment by janiversen** [comment]
@dhoomakethu I added this, hope it is ok.

**Comment by dhoomakethu** [comment]
Earlier `repl` and it's dependencies are installed with `pip install pymodbus[repl]` which should have installed all the requirements. These optional requirements for repl were not installed as part of the normal pymodbus install. Just want to make sure if the same is still being followed or is it going to be installed with normal installation (`pip install pymodbus`)

**Comment by janiversen** [comment]
you can still install with ```pip install pymodbus[repl]``` however even though repl/client/main.py imports pygments it was not in requirements.txt, which was not ok.

**Comment by dhoomakethu** [comment]
Thank you

**Pull request merged**
