### PR TITLE
Simplify server implementation.

### PR DESCRIPTION
**Pull request by janiversen**
Remove sync. server implementation but keep Start<transport>Server as well as StartAsync<transport>Server to allow sync. application to spin up a server.

Changed Async Start<transport>Server to StartAsync<transport>Server to differentiate.

Moved all external symbols to __init__.py to allow consistent implementation independent access for applications.

### CODE REVIEW

**Comment by janiversen** [comment]
@dhoomakethu you might want to check this with your setup before it gets merged.

**Comment by dhoomakethu** [comment]
Will do it today

**Comment by dhoomakethu** [comment]
Not sure if this is being handled in a different branch but can't run the serial version of client
```
python3 examples/client_sync_basic_calls.py --comm serial --framer rtu --log debug
--port /tmp/ttyp0
usage: client_sync_basic_calls.py [-h] [--comm {tcp,udp,serial,tls}] [--framer {ascii,binary,rtu,socket,tls}]
                                  [--log {critical,error,warning,info,debug}] [--port PORT]
client_sync_basic_calls.py: error: argument --port: invalid int value: '/tmp/ttyp0'
```

**Comment by dhoomakethu** [comment]
REPL serial client also seems to be having issues.
```
(pymodbus) ➜  pymodbus git:(dev_server) ✗ pymodbus.console serial --method rtu --port /tmp/ttyp0 --baudrate 9600 --timeout 3

----------------------------------------------------------------------------
__________          _____             .___  __________              .__
\______   \___.__. /     \   ____   __| _/  \______   \ ____ ______ |  |
 |     ___<   |  |/  \ /  \ /  _ \ / __ |    |       _// __ \\____ \|  |
 |    |    \___  /    Y    (  <_> ) /_/ |    |    |   \  ___/|  |_> >  |__
 |____|    / ____\____|__  /\____/\____ | /\ |____|_  /\___  >   __/|____/
           \/            \/            \/ \/        \/     \/|__|
                                        v1.3.0 - [pymodbus, version 3.0.0.dev5]
----------------------------------------------------------------------------

> client.read_holding_registers address=0 count=1 unit=4
TypeError("__init__() got multiple values for argument 'unit'")
>
```

**Comment by janiversen** [comment]
Interesting, let me have a look.

**Comment by janiversen** [comment]
The latter is because you should use slave= not unit= as pr documentation

**Comment by dhoomakethu** [comment]
I could get the serial client example working, however the server threw this error

```
(pymodbus) ➜  pymodbus git:(dev_server) ✗ python3 examples/server_sync.py --comm serial --framer rtu --log debug --port /tmp/ptyp0 --slaves 2 --store sequential
19:08:30 INFO  server_sync:72 ### Create datastore
19:08:30 INFO  server_sync:149 ### start server, listening on /tmp/ptyp0 - serial
19:08:30 DEBUG selector_events:59 Using selector: KqueueSelector
19:08:30 DEBUG async_io:118 Serial connection opened on port: /tmp/ptyp0
19:08:30 DEBUG async_io:444 Serial connection established
19:08:37 DEBUG async_io:210 Handling data: 0x1 0x1 0x0 0x1 0x0 0x1 0xac 0xa
19:08:37 DEBUG rtu_framer:193 Getting Frame - 0x1 0x0 0x1 0x0 0x1
19:08:37 DEBUG factory:220 Factory Request[ReadCoilsRequest': 1]
19:08:37 DEBUG rtu_framer:116 Frame advanced, resetting header!!
19:08:37 ERROR async_io:268 Datastore unable to fulfill request: 'dict' object has no attribute 'validate'; Traceback (most recent call last):
  File "/Users/sanjay/repo/pymodbus/pymodbus/server/async_io.py", line 257, in execute
    response = request.execute(context)
  File "/Users/sanjay/repo/pymodbus/pymodbus/bit_read_message.py", line 164, in execute
    if not context.validate(self.function_code, self.address, self.count):
AttributeError: 'dict' object has no attribute 'validate'

19:08:37 ERROR pdu:118 Exception Response(129, 1, SlaveFailure)
19:08:37 DEBUG async_io:285 send: [Exception Response(129, 1, SlaveFailure)]- b'0181044193'
```

When run against basic sync client example
```
(pymodbus) ➜  pymodbus git:(dev_server) ✗ python3 examples/client_sync_basic_calls.py --comm serial --framer rtu --log debug
--port /tmp/ttyp0
19:08:37 INFO  client_sync:50 ### Create client object
19:08:37 INFO  client_sync:119 ### Client starting
19:08:37 INFO  client_sync_basic_calls:17 ### Reading Coil
19:08:37 DEBUG transaction:130 Current transaction state - IDLE
19:08:37 DEBUG transaction:134 Running transaction 1
19:08:37 DEBUG transaction:291 SEND: 0x1 0x1 0x0 0x1 0x0 0x1 0xac 0xa
19:08:37 DEBUG base:194 New Transaction state "SENDING"
19:08:37 DEBUG transaction:312 Changing transaction state from "SENDING" to "WAITING FOR REPLY"
19:08:37 DEBUG transaction:428 Changing transaction state from "WAITING FOR REPLY" to "PROCESSING REPLY"
19:08:37 DEBUG transaction:327 RECV: 0x1 0x81 0x4 0x41 0x93
19:08:37 DEBUG rtu_framer:193 Getting Frame - 0x81 0x4
19:08:37 DEBUG factory:352 Factory Response[129]
19:08:37 DEBUG rtu_framer:116 Frame advanced, resetting header!!
19:08:37 DEBUG transaction:516 Adding transaction 1
19:08:37 DEBUG transaction:528 Getting transaction 1
19:08:37 DEBUG transaction:234 Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
Traceback (most recent call last):
  File "examples/client_sync_basic_calls.py", line 121, in <module>
    run_client(testclient, modbus_calls=demonstrate_calls)
  File "/Users/sanjay/repo/pymodbus/examples/client_sync.py", line 122, in run_client
    modbus_calls(client)
  File "examples/client_sync_basic_calls.py", line 113, in demonstrate_calls
    handle_coils(client)
  File "examples/client_sync_basic_calls.py", line 19, in handle_coils
    assert not rr.isError()  # test that call was OK
AssertionError
```

**Comment by dhoomakethu** [comment]
> The latter is because you should use slave= not unit= as pr documentation

I will fix this once you merge this branch to `dev`

**Comment by dhoomakethu** [comment]
> And let me see if I can add an Exception if unit= is used.

How about we implicitly use `slave` when `unit` is passed to be backward compatible ?

**Comment by dhoomakethu** [comment]
Async client errors
```
 ✗ python3 examples/client_async_basic_calls.py --comm serial --framer rtu --log debug --port /tmp/ttyp0
19:14:06 INFO  client_async:51 ### Create client object
19:14:06 DEBUG selector_events:59 Using selector: KqueueSelector
19:14:06 DEBUG selector_events:59 Using selector: KqueueSelector
19:14:06 INFO  client_async:121 ### Client starting
19:14:06 DEBUG serial:94 Starting serial connection
19:14:06 WARNING serial:111 Failed to connect: 'ModbusRtuFramer' object is not callable
Traceback (most recent call last):
  File "examples/client_async_basic_calls.py", line 123, in <module>
    asyncio.run(run_client(testclient, modbus_calls=demonstrate_calls))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sanjay/repo/pymodbus/examples/client_async.py", line 123, in run_client
    assert client.protocol
AssertionError
```

**Comment by janiversen** [comment]
> > And let me see if I can add an Exception if unit= is used.
> 
> How about we implicitly use `slave` when `unit` is passed to be backward compatible ?

that is another possibility, let me see what I can come up with. I will add some commits here and request a new review when ready.

**Comment by janiversen** [comment]
The "validate" is very interesting it happens only serial comm. But I can see that tcp have a problem with the rtuframer, which should be ok.

But at least I can reproduce the problems now, I will fix it and get back to you.

**Comment by janiversen** [comment]
@dhoomakethu I think I have solved all the problems you saw and a lot more, there was quite a number of small errors in the library code.

Furthermore I rewrote text_examples.py to give a better coverage.

**Comment by dhoomakethu** [comment]
@janiversen I will give this a try over the weekend. Please do not wait for me if you are comfortable with the changes, we can capture any new findings as separate github issues or enhancements.

**Comment by janiversen** [comment]
Sounds like a good plan, looking forward to hear about your findings. I am working on getting TLS to work in test (adding self-signed certificates) and after that I will write a mock to simulate from serial_asyncio.
.

**Pull request merged**
